# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"H\n\x0fmissile_details\x12\x14\n\x0cmissile_type\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x12\t\n\x01t\x18\x04 \x01(\x05\"%\n\x11survival_response\x12\x10\n\x08is_alive\x18\x01 \x01(\x08\"(\n\x10position_details\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x07\n\x05\x45mpty2A\n\x13\x44\x65\x66\x65nseNotification\x12*\n\x0elaunch_missile\x12\x10.missile_details\x1a\x06.Empty2I\n\x15\x43ommanderNotification\x12\x30\n\x14missile_notification\x12\x10.missile_details\x1a\x06.Empty2\x9e\x01\n\x13SoldierNotification\x12*\n\x0enotify_soldier\x12\x10.missile_details\x1a\x06.Empty\x12,\n\x0esoldier_status\x12\x06.Empty\x1a\x12.survival_response\x12-\n\x10soldier_position\x12\x06.Empty\x1a\x11.position_detailsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MISSILE_DETAILS']._serialized_start=18
  _globals['_MISSILE_DETAILS']._serialized_end=90
  _globals['_SURVIVAL_RESPONSE']._serialized_start=92
  _globals['_SURVIVAL_RESPONSE']._serialized_end=129
  _globals['_POSITION_DETAILS']._serialized_start=131
  _globals['_POSITION_DETAILS']._serialized_end=171
  _globals['_EMPTY']._serialized_start=173
  _globals['_EMPTY']._serialized_end=180
  _globals['_DEFENSENOTIFICATION']._serialized_start=182
  _globals['_DEFENSENOTIFICATION']._serialized_end=247
  _globals['_COMMANDERNOTIFICATION']._serialized_start=249
  _globals['_COMMANDERNOTIFICATION']._serialized_end=322
  _globals['_SOLDIERNOTIFICATION']._serialized_start=325
  _globals['_SOLDIERNOTIFICATION']._serialized_end=483
# @@protoc_insertion_point(module_scope)
